name: extensions_plus
description: "This package provides a powerful collection of extensions for Dart's core types, enabling cleaner and more expressive code."
version: 1.3.0
homepage: "https://github.com/azharbinanwar/extensions_plus"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
